// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUO2im-v3RBsQ3dUYJTeMBn0kcpzYtyDU',
    appId: '1:300710048932:web:e484b252ad6751d3bce231',
    messagingSenderId: '300710048932',
    projectId: 'group6-9f06e',
    authDomain: 'group6-9f06e.firebaseapp.com',
    databaseURL: 'https://group6-9f06e-default-rtdb.firebaseio.com',
    storageBucket: 'group6-9f06e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYO67M0LHrcHS-1o__tHNhBDeh30MSvgk',
    appId: '1:300710048932:android:7aed53e813e6e9aebce231',
    messagingSenderId: '300710048932',
    projectId: 'group6-9f06e',
    databaseURL: 'https://group6-9f06e-default-rtdb.firebaseio.com',
    storageBucket: 'group6-9f06e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6zLNq1-pnbNcFxd2KWche79PRbX7ZYbA',
    appId: '1:300710048932:ios:8bc318e10b412ef9bce231',
    messagingSenderId: '300710048932',
    projectId: 'group6-9f06e',
    databaseURL: 'https://group6-9f06e-default-rtdb.firebaseio.com',
    storageBucket: 'group6-9f06e.firebasestorage.app',
    iosBundleId: 'com.example.group6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6zLNq1-pnbNcFxd2KWche79PRbX7ZYbA',
    appId: '1:300710048932:ios:8bc318e10b412ef9bce231',
    messagingSenderId: '300710048932',
    projectId: 'group6-9f06e',
    databaseURL: 'https://group6-9f06e-default-rtdb.firebaseio.com',
    storageBucket: 'group6-9f06e.firebasestorage.app',
    iosBundleId: 'com.example.group6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUO2im-v3RBsQ3dUYJTeMBn0kcpzYtyDU',
    appId: '1:300710048932:web:18745ad20b408018bce231',
    messagingSenderId: '300710048932',
    projectId: 'group6-9f06e',
    authDomain: 'group6-9f06e.firebaseapp.com',
    databaseURL: 'https://group6-9f06e-default-rtdb.firebaseio.com',
    storageBucket: 'group6-9f06e.firebasestorage.app',
  );
}
